config/routes.rb
Rails.application.routes.draw do
  resources :order_dishes

  resources :orders

  resources :dishes do
    member do
      get 'disable_dish', :as => :disable
    end
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :controllers => {:sessions => "sessions", :registrations => "registrations"}

  put 'users/update_avatar' => 'users#update_avatar', :as => :update_avatar
  resources :users do
    collection do
      post 'toggle_block_ordering', :as => :toggle_block_ordering
    end
  end

  root :to => "orders#index"

end

app/models/order_dish.rb
class OrderDish < ActiveRecord::Base
  belongs_to :order
  belongs_to :dish

  after_destroy :check_order

  def check_order
    if self.order && self.order.order_dishes.empty?
      self.order.destroy
    end
  end
end

app/controllers/order_dishes_controller.rb
class OrderDishesController < ApplicationController
  # GET /order_dishes
  # GET /order_dishes.json
  def index
    @order_dishes = OrderDish.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @order_dishes }
    end
  end

  # GET /order_dishes/1
  # GET /order_dishes/1.json
  def show
    @order_dish = OrderDish.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order_dish }
    end
  end

  # GET /order_dishes/new
  # GET /order_dishes/new.json
  def new
    @order_dish = OrderDish.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order_dish }
    end
  end

  # GET /order_dishes/1/edit
  def edit
    @order_dish = OrderDish.find(params[:id])
  end

  # POST /order_dishes
  # POST /order_dishes.json
  def create
    @order_dish = OrderDish.new(params[:order_dish])

    respond_to do |format|
      if @order_dish.save
        format.html { redirect_to @order_dish, notice: 'Order dish was successfully created.' }
        format.json { render json: @order_dish, status: :created, location: @order_dish }
      else
        format.html { render action: "new" }
        format.json { render json: @order_dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /order_dishes/1
  # PUT /order_dishes/1.json
  def update
    @order_dish = OrderDish.find(params[:id])

    respond_to do |format|
      if @order_dish.update_attributes(params[:order_dish])
        format.html { redirect_to @order_dish, notice: 'Order dish was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order_dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_dishes/1
  # DELETE /order_dishes/1.json
  def destroy
    @order_dish = OrderDish.find(params[:id])
    @order_dish.destroy

    respond_to do |format|
      format.html { redirect_to order_dishes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/order_dishes_helper.rb
module OrderDishesHelper
end

app/views/order_dishes/_form.html.haml
= simple_form_for @order_dish, :html => { :class => 'form-horizontal' } do |f|
  = f.input :order_id
  = f.input :dish_id
  = f.input :number
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), order_dishes_path, :class => 'btn'

app/views/order_dishes/edit.html.haml
- model_class = OrderDish
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/order_dishes/index.html.haml
- model_class = OrderDish
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:order_id)
      %th= model_class.human_attribute_name(:dish_id)
      %th= model_class.human_attribute_name(:number)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @order_dishes.each do |order_dish|
      %tr
        %td= link_to order_dish.id, order_dish_path(order_dish)
        %td= order_dish.order_id
        %td= order_dish.dish_id
        %td= order_dish.number
        %td=l order_dish.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_order_dish_path(order_dish), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), order_dish_path(order_dish), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_order_dish_path, :class => 'btn btn-primary'

app/views/order_dishes/new.html.haml
- model_class = OrderDish
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/order_dishes/show.html.haml
- model_class = OrderDish
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:order_id) + ':'
  %br
  = @order_dish.order_id
%p
  %strong= model_class.human_attribute_name(:dish_id) + ':'
  %br
  = @order_dish.dish_id
%p
  %strong= model_class.human_attribute_name(:number) + ':'
  %br
  = @order_dish.number

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), order_dishes_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_order_dish_path(@order_dish), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), order_dish_path(@order_dish), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'