config/routes.rb
Rails.application.routes.draw do
  resources :order_dishes

  resources :orders

  resources :dishes do
    member do
      get 'disable_dish', :as => :disable
    end
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :controllers => {:sessions => "sessions", :registrations => "registrations"}

  put 'users/update_avatar' => 'users#update_avatar', :as => :update_avatar
  resources :users do
    collection do
      post 'toggle_block_ordering', :as => :toggle_block_ordering
    end
  end

  root :to => "orders#index"

end

app/models/user.rb
# encoding: utf-8
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model

  validates_presence_of :nickname
  validates_uniqueness_of :nickname, :email

  belongs_to :department

  has_many :orders

  ADMIN_USER = %w(TestUser)

  def admin?
    ADMIN_USER.include? nickname
  end

  def can_manage_dishes?
    ADMIN_USER.include? nickname
  end


end

app/controllers/users_controller.rb
#encoding: utf-8
class UsersController < ApplicationController

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    authorize! :edit, @user
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: '用户信息更新成功.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = current_user

    respond_to do |format|
      if @user.update_with_password(params[:user])
        format.html { redirect_to new_user_session_path , notice: '密码更新成功， 请重新登陆' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end

  end

  def update_avatar
    @user = current_user
    respond_to do |format|
      if @user.update_without_password(params[:user])
        format.html { render :edit , notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def toggle_block_ordering
    return unless current_user.can_manage_dishes?
    Setting.toggle_block_ordering!
  end

  ## TODO
  ## Strong Parameters
  ## https://edgeapi.rubyonrails.org/classes/ActionController/StrongParameters.html

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= simple_form_for @user, :url => update_avatar_path, :html => { :multipart => true, :class => 'edit-user form-horizontal' } do |f|
  = f.input :nickname
  = f.association :department
  .form-actions
    = f.submit '更新', :class => 'btn-large btn-primary'

= simple_form_for @user, :url => user_path(@user), :method => :put , :html => { :multipart => true, :class => 'edit-user form-horizontal' } do |f|
  = f.input :current_password, :label => '当前密码'
  = f.input :password, :label => '新密码'
  = f.input :password_confirmation, :label => '新密码确认'
  .form-actions
    = f.submit '更新密码', :class => 'btn-large btn-primary'

app/views/users/edit.html.haml
- model_class = User
.page-header
  %h3 更改设置
= render :partial => "form"

app/views/users/index.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:avatar)
      %th= model_class.human_attribute_name(:nickname)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @users.each do |user|
      %tr
        %td= thumb_avatar user
        %td= user.nickname
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(user), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, 
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_user_path, :class => 'btn btn-primary'

app/views/users/new.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human

= simple_form_for @user, :html => { :multipart => true, :class => 'edit-user form-horizontal' } do |f|
  = f.input :nickname
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn'

app/views/users/show.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:nickname) + ':'
  %br
  = @user.nickname
%p
  %strong= model_class.human_attribute_name(:avatar) + ':'
  %br
  = large_avatar @user
  = medium_avatar @user
  = thumb_avatar @user
%p
  %strong= model_class.human_attribute_name(:email) + ':'
  %br
  = @user.email


.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), users_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(@user), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(@user), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/users/toggle_block_ordering.js.haml
- if Setting.block_ordering
  - btnText = '开放点餐'
  - alertText = '现在已经禁止点餐。用户将不能点餐'
- else
  - btnText = '禁止点餐'
  - alertText = '现在已经开放点餐。用户可以点餐'

$('.toggle_block_ordering.btn').text(" #{ btnText } ")
alert(" #{ alertText } ")