config/routes.rb
Rails.application.routes.draw do
  resources :order_dishes

  resources :orders

  resources :dishes do
    member do
      get 'disable_dish', :as => :disable
    end
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :controllers => {:sessions => "sessions", :registrations => "registrations"}

  put 'users/update_avatar' => 'users#update_avatar', :as => :update_avatar
  resources :users do
    collection do
      post 'toggle_block_ordering', :as => :toggle_block_ordering
    end
  end

  root :to => "orders#index"

end

app/models/order.rb
class Order < ActiveRecord::Base

  has_many :order_dishes, :dependent => :destroy

  belongs_to :user


end

app/controllers/orders_controller.rb
# encoding: utf-8
class OrdersController < ApplicationController
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.where('updated_at > ?', Time.now - 4.hours ).all
    # @orders = Order.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
    authorize! :edit, @order
  end

  # POST /orders
  # POST /orders.json
  def create
    unless Setting.block_ordering
      @order = Order.new
      params[:dishes].each { |k, v|
        v = v.to_i
        next if v == 0
        @order.order_dishes.build({ dish_id: k, number: v})
      }
      @order.user = current_user

      respond_to do |format|
        if @order.save
          format.html { redirect_to orders_url, notice: '成功提交.' }
          format.json { render json: @order, status: :created, location: @order }
        else
          format.html { render action: "new" }
          format.json { render json: @order.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to orders_url, notice: '已超过点餐时间，点餐失败'
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    unless Setting.block_ordering
      old_order = Order.find(params[:id])
      old_order.destroy if old_order

      @order = Order.new
      params[:dishes].each { |k, v|
        v = v.to_i
        next if v == 0
        @order.order_dishes.build({ dish_id: k, number: v})
      }
      @order.user = current_user

      respond_to do |format|
        if @order.save
          format.html { redirect_to orders_url, notice: '成功更新.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @order.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to orders_url, notice: '已超过点餐时间，修改失败'
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    authorize! :destroy, @order
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.haml
= simple_form_for @order, :html => { :class => 'form-horizontal order-form' } do |f|
  %table.table.table-striped
    %thead
      %tr
        %th 菜名
        %th 价格(元)
        %th 描述
        %th 份数
    %tbody
      - Dish.active.all.sort_by { |e| -e.price }.each do |dish|
        %tr
          %td= dish.name
          %td= dish.price
          %td= dish.desc
          %td= number_field_tag "dishes[#{dish.id}]", ( @order.order_dishes.find_by_dish_id(dish.id) || { :number => 0 } )[:number]

  .form-actions
    - if Setting.block_ordering
      %p.label.label-important(style="font-size: 1.2em; line-height: 2em;")
        = Setting.now_is_blocking_ordering_you_are_late
    - else
      = f.button :submit, '提交订单', :class => 'btn-primary btn-large pull-left'

app/views/orders/edit.html.haml
- model_class = Order
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/orders/index.html.haml
- model_class = Order
.page-header
  %h3 4小时内所有订单

%ul.nav.nav-tabs#myTab
  %li.active
    %a(href="#home") 最新点餐
  %li
    %a(href="#popular") 最受欢迎的菜
  %li
    %a(href="#by_department") 部门金额
.tab-content
  .tab-pane.active#home
    %table.table.table-striped
      %thead
        %tr
          %th 用户名
          %th 部门
          %th(style="width: 206px;") 点菜
          %th
          %th
      %tbody
        - @orders.each do |order|
          %tr(class="#{order.user == current_user ? 'my-order' : '' }")
            %td= User.find(order.user_id).nickname
            %td= User.find(order.user_id).department.try(:name)
            %td= order.order_dishes.collect {|od| if od.dish then od.dish.name + ' ' + od.number.to_s + '份' end }.join(',')
            %td=l order.created_at
            %td
              - if can? :edit, order
                = link_to '编辑', edit_order_path(order), :class => 'btn btn-mini'
                = link_to '删除', order_path(order), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'
  .tab-pane#popular
    - dishes_number_by_name = @orders.inject({}) do |mem, order| 
      - order.order_dishes.each do | order_dish |
        - mem[order_dish.dish] ||= 0
        - mem[order_dish.dish] = mem[order_dish.dish] + order_dish.number
      - mem
    - dishes_number_by_name = dishes_number_by_name.sort_by { |k,v| v }.reverse
    %table.table.table-striped
      %thead
        %tr
          %th 菜名
          %th 份数
      %tbody
        - dishes_number_by_name.each do |k, v|
          %tr
            %th= if k then k.name end
            %th= v
  .tab-pane#by_department
    - money_by_department = @orders.inject({}) do |mem, order|
      - department = order.user.department
      - if department
        - mem[department] ||= 0
        - mem[department] += order.order_dishes.inject(0) do |m, od|
          - m += od.dish.price * od.number
          - m
      - mem

    %table.table.table-striped
      %thead
        %tr
          %th 部门
          %th 总金额(元)
      %tbody
        - money_by_department.each do |k, v|
          %tr
            %th= k.name
            %th= v

= link_to ( Setting.block_ordering ? '开放点餐' : '禁止点餐' ), 
  toggle_block_ordering_users_path, 
  :class => 'btn btn-primary btn-large toggle_block_ordering', :method => :post, :remote => true if current_user.can_manage_dishes?

app/views/orders/new.html.haml
- model_class = Order
.page-header
  %h3 今日菜单
= render :partial => "form"

app/views/orders/show.html.haml
- model_class = Order
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:user_id) + ':'
  %br
  = @order.user_id

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), orders_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_order_path(@order), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), order_path(@order), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'