config/routes.rb
Rails.application.routes.draw do
  resources :order_dishes

  resources :orders

  resources :dishes do
    member do
      get 'disable_dish', :as => :disable
    end
  end

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :controllers => {:sessions => "sessions", :registrations => "registrations"}

  put 'users/update_avatar' => 'users#update_avatar', :as => :update_avatar
  resources :users do
    collection do
      post 'toggle_block_ordering', :as => :toggle_block_ordering
    end
  end

  root :to => "orders#index"

end

app/models/dish.rb
class Dish < ActiveRecord::Base

  has_many :order_dishes, :dependent => :destroy

  scope :active, :conditions => "#{Dish.table_name}.disable = false"

end

app/controllers/dishes_controller.rb
# encoding: utf-8
class DishesController < ApplicationController
  # GET /dishes
  # GET /dishes.json
  def index
    @dishes = Dish.order(:disable).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dishes }
    end
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show
    @dish = Dish.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dish }
    end
  end

  # GET /dishes/new
  # GET /dishes/new.json
  def new
    @dish = Dish.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dish }
    end
  end

  # GET /dishes/1/edit
  def edit
    @dish = Dish.find(params[:id])
  end

  # POST /dishes
  # POST /dishes.json
  def create
    @dish = Dish.new(params[:dish])

    respond_to do |format|
      if @dish.save
        format.html { redirect_to dishes_url, notice: 'Dish was successfully created.' }
        format.json { render json: @dish, status: :created, location: @dish }
      else
        format.html { render action: "new" }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dishes/1
  # PUT /dishes/1.json
  def update
    @dish = Dish.find(params[:id])

    respond_to do |format|
      if @dish.update_attributes(params[:dish])
        format.html { redirect_to dishes_url, notice: 'Dish was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @dish = Dish.find(params[:id])
    @dish.destroy

    respond_to do |format|
      format.html { redirect_to dishes_url }
      format.json { head :no_content }
    end
  end

  def disable_dish
    @dish = Dish.find(params[:id])
    @dish.disable = ( params[:disable] == 'true' ? true : false )
    @dish.order_dishes.clear if @dish.disable
    respond_to do |format|
      if @dish.save
        format.html { redirect_to dishes_url, notice: '菜单已禁用.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/_form.html.haml
= simple_form_for @dish, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = f.input :desc, :input_html => { :rows => 3 }
  = f.input :price
  = f.input :disable
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), dishes_path, :class => 'btn'

app/views/dishes/edit.html.haml
- model_class = Dish
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/dishes/index.html.haml
- model_class = Dish
.page-header
  %h3 所有菜单
%p.label.label-info 启用的菜单将可以被用户点餐，禁用的菜单用户不可以点。
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:desc)
      %th= model_class.human_attribute_name(:price)
      %th 是否启用
      %th= model_class.human_attribute_name(:created_at)
      %th 动作
  %tbody
    - @dishes.each do |dish|
      %tr
        %td= dish.name
        %td= dish.desc
        %td= dish.price
        %td
          - if dish.disable
            %span.label.label 已禁用
          - else 
            %span.label.label-success 已启用
        %td=l dish.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_dish_path(dish), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), dish_path(dish), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'
          = link_to ( dish.disable ? '启用' : '禁用' ), disable_dish_path(dish, :disable => !dish.disable ), :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_dish_path, :class => 'btn btn-primary'

app/views/dishes/new.html.haml
- model_class = Dish
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/dishes/show.html.haml
- model_class = Dish
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @dish.name
%p
  %strong= model_class.human_attribute_name(:desc) + ':'
  %br
  = @dish.desc
%p
  %strong= model_class.human_attribute_name(:price) + ':'
  %br
  = @dish.price

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), dishes_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_dish_path(@dish), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), dish_path(@dish), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'